remote_theme: MicrosoftLearning/Jekyll-Theme
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: Toshimi Hatanaka (Microsoft Worldwide Learning)
twitter_username: toshimin8
github_username:  mocaomochi
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
      line_numbers: true